services:
  - type: web
    name: mastenko-store
    runtime: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_VERSION
        value: 24.12.0
      - key: ADMIN_USER
        sync: false
      - key: ADMIN_PASSWORD
        sync: false
